# Generated by Django 2.1.3 on 2018-12-12 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sentiment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=256, verbose_name='配置项')),
                ('value', models.TextField(verbose_name='值')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='修改日期')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
